* Encoding: UTF-8.

FACTOR
  /VARIABLES CYNewWorldOrder CYSARS CYPearlHarbor CYMLK CYMoon CYArea51 CYJFK CY911 CYRoswell 
    CYDiana CYOkla CYCoke
  /MISSING LISTWISE 
  /ANALYSIS CYNewWorldOrder CYSARS CYPearlHarbor CYMLK CYMoon CYArea51 CYJFK CY911 CYRoswell 
    CYDiana CYOkla CYCoke
  /PRINT UNIVARIATE INITIAL EXTRACTION ROTATION
  /CRITERIA MINEIGEN(1) ITERATE(25)
  /EXTRACTION PAF
  /CRITERIA KAISER  ITERATE(25) DELTA(0)
  /ROTATION OBLIMIN
  /METHOD=CORRELATION.
